nodered:
    build:
      context: .
      dockerfile: Dockerfile.nodered
    ports:
      - "${NODERED_HOST_PORT:-1880}:1880"
    volumes:
      - ./nodered-data:/data
    user: "root"
    environment:
      - NODE_ENV=development
      - FLOWS=flows.json